export default {
  userAuth: {
    email: "",
    passwordHash: "",
    userLevel: "",
    isActive: "",
  },
  userInfo: {
    id: "",
    firstName: "",
    lastName: "",
    email: "",
    phone: "",
    location: "",
    profilePicture: "",
    personalLinks: "",
    age: "",
  },
  portfolio: {
    title: "",
    images: "",
    price: "",
    location: "",
    isRentalOrSale: "",
    description: "",
    deedType: "",
    portfolioType: "",
    netSize: "",
    numberOfRooms: "",
    ageOfTheSctructure: "",
    floorNumber: "",
    isSuitableToMorgage: "",
  },
};
